name: generate snk animation

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nerina1241
          svg_out_path: snk.svg
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: main
          github_token: ${{ github.token }}
